// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/**
 * @title IGroth16Verifier
 * @dev Interface for zkSNARK Groth16 proof verification
 * This will be generated by Noir compiler
 */
interface IGroth16Verifier {
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external view returns (bool);
}
